### ISSUE TITLE
Using Trazzle w/Robotlegs

### ISSUE THREAD

**Issue by marr** [jankeesvw/LogMeister#2]
Hi there! Cool looking util here. I haven't used Trazzle before but I am use to SOSMax and I see you support that too.

I have included the logmeister.swc file in my project and have used the following lines to try to setup the logger:

LogMeister.addLogger(new TrazzleConnector(contextView.stage, "My Project"));
LogMeister.addLogger(new SosMaxConnector());

I have verified my import statements are correct and I can build without an issue. However any calls to use the logging are not actually working.

log('CTOR'); inside my Context constructor has no affect.

Thanks for any help.

**Comment by jankeesvw** [comment]
Hi There,

Thanks for the comment, 

The new Trazzle has something strange, you need to add debug=true to the compiler arguments... Could you try that?

Does the SOSMax logging work? 

Let me know if this works for you,

**Comment by marr** [comment]
I was having some problems with my project layout but I believe this is no longer an issue.

**Comment by jankeesvw** [comment]
Cool, then I close this issue.
