### ISSUE TITLE
Little bug in FirebugConnector

### ISSUE THREAD

**Issue by jeromedecoster** [jankeesvw/LogMeister#4]
Hello,

There is a little bug in the FirebugConnector at this line:
https://github.com/base42/LogMeister/blob/master/source/logmeister/logmeister/connectors/FirebugConnector.as#L43

Shouldn't be this ? :
ExternalInterface.call(LOG_FUNCTION, String(args));

J.

**Comment by jankeesvw** [comment]
Hi Jerome, 

I just uploaded a fix (LogMeister version 1.8.1)

Thanks for reporting!
