### ISSUE TITLE
swc should not contain 3rd party libraries

### ISSUE THREAD

**Issue by fljot** [jankeesvw/LogMeister#9]
Right now (v 1.8.2) the precompiled swc contains all kinds of 3rd party libraries (such as MonsterDebugger packaged). It should not.
- There's no ant build script could be found so I can't really update that. Current workaround: use source code instead of swc.

**Comment by jankeesvw** [comment]
i understand the issue, but its for users much easier to have one .swc with everything, if you don't use the libraries, they don't get compiled anyway... right?

**Comment by fljot** [comment]
What if, let's say, DeMonsters fix their stuff?

**Comment by jankeesvw** [comment]
what do you mean?

**Comment by fljot** [comment]
If DeMonsters release a fix/update for their MonsterDebugger — you HAVE to update the whole logger swc in order to embed that new code. This won't be the case if swc has not 3rd party code embedded.
And don't forget about all possible licence issues.

**Comment by jankeesvw** [comment]
i know but i think that's one of the things i want to keep this way, this is how i like it.. Sorry.
